#!/bin/bash

set -e -u -o pipefail
# set -x

info() {
    echo -e "\x1b[32m\xE2\x87\x92 $1\x1b[0m"
}

error() {
    echo -e "\x1b[97m\x1b[41m\x21\x1b[0m \x1b[31m$1\x1b[0m" 1>&2
    exit 1
}

is_install() {
    command -v "$1" > /dev/null 2>&1 || error "'$1' (command not found)"
}

check_deps() {
  is_install curl
  is_install cargo
}

main() {
    info "Checking dependencies..."
    check_deps

    local tempdir=$(mktemp -d XXXXXX)

    info "Fetch source code..."
    curl -s -L https://api.github.com/repos/mickaelvieira/vagment/tarball | tar -C $tempdir -xzf -

    info "Compiling application..."
    cd ${tempdir}/mickaelvieira-*
    cargo build --release

    info "Cleaning up..."
    mv target/release/vagment ../..
    cd ../..
    rm -rf "${tempdir}/"

    info "Application ready..."
    ./vagment --help
}

main
